version: "3.8"

services:
  backend:
    build: ./backend
    volumes:
      - ./backend:/app
    ports:
      - "3000:3000"
    env_file:
      - .env
    depends_on:
      - mongo
      - postgres

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
      target: build
    image: frontend-build
    command: echo "Build only"

  nginx:
    build:
      context: ./nginx
      dockerfile: Dockerfile
    ports:
      - "80:80"
    depends_on:
      - frontend

  mongo:
    image: mongo
    container_name: mongodb
    ports:
      - "27017:27017"
    volumes:
      - ./database/mongo-data:/data/db

  postgres:
    image: postgres
    container_name: postgresdb
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: portfolio
    ports:
      - "5432:5432"
    volumes:
      - ./database/pg-data:/var/lib/postgresql/data
